nominals/urls.py
from django.urls import path

from .views import (CreateTransaction, EditTransaction, FinaliseFY,
                    LoadNominal, NominalCreate, NominalDetail, NominalEdit,
                    NominalList, RollbackFY, TransactionEnquiry, TrialBalance,
                    ViewTransaction, VoidTransaction)

app_name = "nominals"
urlpatterns = [
    path("create", CreateTransaction.as_view(), name="create"),
    path("edit/<int:pk>", EditTransaction.as_view(), name="edit"),
    path("view/<int:pk>", ViewTransaction.as_view(), name="view"),
    path("void/<int:pk>", VoidTransaction.as_view(), name="void"),
    path("trial_balance", TrialBalance.as_view(), name="trial_balance"),

    path("finalise_fy", FinaliseFY.as_view(), name="finalise_fy"),
    path("rollback_fy", RollbackFY.as_view(), name="rollback_fy"),

    path("nominals_list", NominalList.as_view(), name="nominals_list"),
    path("nominal_detail/<int:pk>", NominalDetail.as_view(), name="nominal_detail"),
    path("nominal_edit/<int:pk>", NominalEdit.as_view(), name="nominal_edit"),
    path("nominal_create", NominalCreate.as_view(), name="nominal_create"),

    path("load_nominals", LoadNominal.as_view(), name="load_nominals"),
    path("transactions", TransactionEnquiry.as_view(), name="transaction_enquiry"),
]

proj/urls.py
from django.contrib import admin
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic.base import RedirectView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cashbook/', include("cashbook.urls")),
    path('contacts/', include("contacts.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('nominals/', include("nominals.urls")),
    path('purchases/', include("purchases.urls")),
    path('sales/', include("sales.urls")),
    path('controls/', include("controls.urls")),
    path('users/', include("users.urls")),
    path('users/', include("django.contrib.auth.urls")),
    path('vat/', include("vat.urls")),
    path('', RedirectView.as_view(url=reverse_lazy(
        "dashboard:dashboard")), name="home")
]

vat/urls.py
from django.urls import path

from vat.views import (LoadVatCodes, VatCreate, VatDetail, VatList,
                       VatTransactionEnquiry, VatUpdate)

app_name = "vat"
urlpatterns = [
    path("load_vat_codes", LoadVatCodes.as_view(), name="load_vat_codes"),
    path("vat_detail/<int:pk>", VatDetail.as_view(), name="vat_detail"),
    path("vat_create", VatCreate.as_view(), name="vat_create"),
    path("vat_edit/<int:pk>", VatUpdate.as_view(), name="vat_edit"),
    path("vat_list", VatList.as_view(), name="vat_list"),
    path("transactions", VatTransactionEnquiry.as_view(), name="transaction_enquiry"),
]

nominals/models.py
import calendar
from datetime import date
from itertools import groupby

from accountancy.helpers import bulk_delete_with_history
from accountancy.mixins import (AuditMixin, BaseNominalTransactionMixin,
                                BaseNominalTransactionPerLineMixin,
                                VatTransactionMixin)
from accountancy.models import (MultiLedgerTransactions, NonAuditQuerySet,
                                Transaction, TransactionHeader,
                                TransactionLine, UIDecimalField)
from cashbook.models import CashBookHeader
from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from mptt.models import MPTTModel, TreeForeignKey
from purchases.models import PurchaseHeader
from sales.models import SaleHeader
from simple_history import register
from vat.models import Vat


def last_day_of_month(period):
    last_month_of_fy = period.month_start - relativedelta(months=+1)
    month, day = calendar.monthrange(
        last_month_of_fy.year, last_month_of_fy.month)
    return date(last_month_of_fy.year, last_month_of_fy.month, day)


class Nominal(AuditMixin, MPTTModel):
    NOMINAL_TYPES = [
        ("pl", "profit and loss"),
        ("b", "balance sheet")
    ]
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    type = models.CharField(
        max_length=2, choices=NOMINAL_TYPES, null=True, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'parent'], name="nominal_unique")
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("nominals:nominal_detail", kwargs={"pk": self.pk})


class NominalTransaction(Transaction):
    module = "NL"


class Journal(
        VatTransactionMixin,
        BaseNominalTransactionPerLineMixin,
        BaseNominalTransactionMixin,
        NominalTransaction):
    pass


class ModuleTransactions:
    analysis_required = [
        ('nj', 'Journal')
    ]
    lines_required = [
        ('nj', 'Journal')
    ]
    positives = ['nj']
    negatives = []
    credits = []
    debits = ['nj']
    payment_types = []
    types = analysis_required + [("nbf", "Nominal Brought Forward")]


class NominalHeader(ModuleTransactions, TransactionHeader):
    vat_types = [
        ("i", "Input"),
        ("o", "Output")
    ]
    type = models.CharField(
        max_length=3,
        choices=ModuleTransactions.types
    )
    vat_type = models.CharField(
        max_length=2,
        choices=vat_types,
        null=True,
        blank=True
    )

    class Meta:
        permissions = [
            # enquiry perms
            ("view_transactions_enquiry", "Can view transactions"),
            # report perms
            ("view_trial_balance_report", "Can view trial balance report"),
            # transactions
            ("create_journal_transaction", "Can create journal"),
            ("edit_journal_transaction", "Can edit journal"),
            ("view_journal_transaction", "Can view journal"),
            ("void_journal_transaction", "Can void journal"),
        ]

    def get_type_transaction(self):
        if self.type == "nj":
            return Journal(header=self)

    def get_absolute_url(self):
        return reverse("nominals:view", kwargs={"pk": self.pk})


class NominalLine(ModuleTransactions, TransactionLine):
    header = models.ForeignKey(NominalHeader, on_delete=models.CASCADE)
    nominal = models.ForeignKey(Nominal, on_delete=models.CASCADE)
    vat_code = models.ForeignKey(
        Vat, on_delete=models.SET_NULL, null=True, verbose_name="Vat Code")
    goods_nominal_transaction = models.ForeignKey(
        'nominals.NominalTransaction', null=True, on_delete=models.SET_NULL, related_name="nominal_good_line")
    vat_nominal_transaction = models.ForeignKey(
        'nominals.NominalTransaction', null=True, on_delete=models.SET_NULL, related_name="nominal_vat_line")
    vat_transaction = models.ForeignKey(
        'vat.VatTransaction', null=True, blank=True, on_delete=models.SET_NULL, related_name="nominal_line_vat_transaction")
    type = models.CharField(
        max_length=3,
        choices=NominalHeader.types
        # see note on parent class for more info
    )

    @classmethod
    def fields_to_update(cls):
        return [
            "line_no",
            'description',
            'goods',
            'vat',
            "nominal",
            "vat_code",
            "type"
        ]


class NominalTransactionQuerySet(NonAuditQuerySet):

    def rollback_fy(self, financial_year):
        """
        Delete the brought forwards for `financial_year` which is an integer for the year e.g. 2020
        Ensure you pass therefore fy.financial_year, where fy is an instance of model FinancialYear,
        and not fy.

        E.g. 
        financial_year = 2020
        So will delete bfs posted into 01 2020
        Allowing the user to post back into FY 2019
        Afterwards carrying forward again i.e. doing a year end which
        will again post the bfs into 01 2020
        """
        self.filter(module="NL").filter(type="nbf").filter(
            period__fy__financial_year__gte=financial_year).delete()
        NominalHeader.objects.filter(type="nbf").filter(
            period__fy__financial_year__gte=financial_year).delete()

    def carry_forward(self, fy, period):
        """
        Calculate the carry forwards from FY so we can post them
        as brought forwards into `period`
        """
        # REMEMBER TO LOCK POSTS IN CALLING CODE I.E. THE VIEW
        retained_earnings, system_suspense = Nominal.objects.filter(
            name__in=["Retained Earnings", "System Suspense Account"]).order_by("name")
        pl = self.filter(period__fy=fy).filter(
            nominal__type="pl").aggregate(profit=Sum("value"))
        balance_sheet = self.filter(period__fy=fy).filter(
            nominal__type="b").values("nominal").annotate(total=Sum("value"))
        """
        We only really care about posting nominal transactions but nominaltransaction.header is
        unique per MODULE.  Since we want module=NL we create a blank header to satisfy this requirement.
        """
        header = NominalHeader.objects.create(
            date=last_day_of_month(period),
            ref=f"YEAR END {str(fy)}",
            period=period,
            total=0,
            status="c",
            type="nbf",
            vat_type=None,
        )
        header = header.pk
        line = 1
        bfs = []
        prev_retained_earnings_bf = False
        retained_earnings_bf = None
        if pl["profit"]:
            # i.e. a non zero profit
            # which means a profit or loss
            retained_earnings_bf = NominalTransaction.brought_forward(
                header, line, fy, period, pl["profit"], retained_earnings.pk
            )
            line += 1
        if balance_sheet:
            for nominal_pk_and_total in balance_sheet:
                if nominal_pk_and_total["nominal"] == retained_earnings.pk:
                    prev_retained_earnings_bf = True
                    if retained_earnings_bf:
                        retained_earnings_bf.value += nominal_pk_and_total["total"]
                        bf = retained_earnings_bf
                    else:
                        bf = retained_earnings_bf = NominalTransaction.brought_forward(
                            header, line, fy, period, nominal_pk_and_total["total"], nominal_pk_and_total["nominal"])
                else:
                    bf = NominalTransaction.brought_forward(
                        header, line, fy, period, nominal_pk_and_total["total"], nominal_pk_and_total["nominal"])
                bfs.append(bf)
                line += 1
            if not prev_retained_earnings_bf:
                if retained_earnings_bf:
                    bfs.append(retained_earnings_bf)
        else:
            if retained_earnings_bf:
                # i do not think this is possible but include in case i'm not seeing something
                # a profit or loss for the year means transactions which updated the balance sheet
                # otherwise they'd all cancel to zero
                # and if anything has ever updated the nominal it will always be c/f
                # so even if nothing is ever again posted in the balance sheet nominal there is always at least the c/f
                # thus i do not think this line of code can ever be hit
                # log this !
                bfs.append(retained_earnings_bf)
            else:
                # i.e. no transactions at all !
                # this is unlikely but was spotted during testing
                # a FY is considered finalised unless there is a year end posting
                # so we just post a zero value transaction to the suspense account
                # it will be invisible to the users
                bf = NominalTransaction.brought_forward(
                    header, line, fy, period, 0, system_suspense.pk
                )
                bfs.append(bf)
        self.bulk_create(bfs)


class NominalTransaction(MultiLedgerTransactions):
    all_module_types = (
        PurchaseHeader.analysis_required +
        NominalHeader.types +
        SaleHeader.analysis_required +
        CashBookHeader.analysis_required
    )
    nominal = models.ForeignKey(Nominal, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=all_module_types)
    value = models.DecimalField(
        decimal_places=2,
        max_digits=10,
        default=0
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(

nominals/templates/nominals/create.html
{% extends 'accountancy/create.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'purchases/css/purchase_input.css' %}">
{% endblock extra_head %}

{% block modal_forms %}
    {% include 'accountancy/on_the_fly.html' %}
{% endblock modal_forms %}

{% block extra_js %}
    {% include 'accountancy/grid_js.html' with header_form=header_form %}
    <script src="{% static 'purchases/js/on_the_fly.js' %}"></script>
    <script>
        $(document).ready(function(){
            $("select[name='header-vat_type']").selectize({
                "allowEmptyOption": true,
                "copyClassesToDropdown": false
            });
        });
    </script>
{% endblock extra_js %}

nominals/templates/nominals/edit.html
{% extends 'accountancy/edit.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'purchases/css/purchase_input.css' %}">
    <link rel="stylesheet" href="{% static 'accountancy/css/audit.css' %}">
{% endblock extra_head %}

{% block buttons_footer %}
<div class="d-flex justify-content-between align-items-center p-2 border bg-white">
    <div>
        <button type="button" class="btn btn-primary btn-sm" data-backdrop="false" data-toggle="modal" data-target="#auditModal">
            Audit
        </button>
    </div>
    <div>
        <button type="submit" class="btn btn-success xero-btn approve" name="approve" value="do_not_add_another">Save</button>
    </div>
</div>
{% endblock buttons_footer %}

{% block modal_forms %}
    {% include 'accountancy/on_the_fly.html' %}
    {% include 'accountancy/audit_transaction.html' %}
{% endblock modal_forms %}

{% block extra_js %}
    {% include 'accountancy/grid_js.html' with header_form=header_form %}
    <script src="{% static 'purchases/js/on_the_fly.js' %}"></script>
    <script>
        {% include "accountancy/audit.js" %}
    </script>
    <script src="{% static 'accountancy/js/audit_transaction.js' %}"></script>
{% endblock extra_js %}

{% block module_js %}
    <script>
        $(document).ready(function(){
            $("select[name='header-vat_type']").selectize({
                "allowEmptyOption": true,
                "copyClassesToDropdown": false
            });
        });
    </script>
{% endblock module_js %}

nominals/templates/nominals/finalise_fy.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'accountancy/css/selectize.css' %}">
<style>
    .modal-footer{
        border: 0 !important;
    }
</style>
{% endblock head %}

{% block content %}
<div class="cont">
    <div>
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="w-75">
                    <div class="border rounded p-4 mt-5">
                        <h1 class="h4 font-weight-bold text-capitalize">{{ view.title }}</h1>
                        <div class="mt-4">
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger">
                                    <div class="row">
                                        <div class="col">
                                            <ul class="list-unstyled m-0 p-0">
                                                {% for error in form.non_field_errors %}
                                                    <li>{{ error }}</li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                            {% load crispy_forms_tags %}
                            {% crispy form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script src="{% static 'js/selectize.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $("form select").selectize();
        var val = $("select[name='financial_year']").val();
        if(!val){
            $("input[name='complete']").prop("disabled", true);
        }
    });
</script>
{% endblock js %}

nominals/templates/nominals/nominal_create_and_edit.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'accountancy/css/selectize.css' %}">
<style>
    .modal-footer{
        border: 0 !important;
    }
</style>
{% endblock head %}

{% block content %}
<div class="cont">
    <div>
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="w-75">
                    <div class="border rounded p-4 mt-5">
                        <h1 class="h4 font-weight-bold">{% firstof nominal 'Create Nominal' %}</h1>
                        <div class="mt-4">
                            {% load crispy_forms_tags %}
                            {% crispy form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script src="{% static 'js/selectize.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $("form select").selectize();
    });
</script>
{% endblock js %}

nominals/templates/nominals/nominal_detail.html
{% extends 'accountancy/single_object_detail_with_audit.html' %}

{% block content %}

<div class="cont">
    <div>
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="w-75">
                    <div class="border rounded p-4 mt-5">
                        <h1 class="h4 font-weight-bold">{{ nominal }}</h1>
                        <div class="font-italic">
                            Details to add at later date
                        </div>
                        <div class="mt-3">
                            <button class="btn btn-primary mr-2 audit-btn">Audit</button>
                            <a class="btn btn-success" href="{% url 'nominals:nominal_edit' pk=nominal.pk %}">Edit</a>
                        </div>
                        <div class="d-none mt-3 audit_section p-3 border rounded">
                            <h2 class="h4 font-weight-bold">Audit</h2>
                            {% include 'accountancy/audit.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

nominals/templates/nominals/nominal_list.html
{% extends 'base.html' %}

{% block content %}

<div class="cont">
    <div>
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="w-75">
                    <div class="border rounded p-4 mt-5">
                        <div class="d-flex justify-content-between">
                            <h1 class="h4 font-weight-bold">Nominal List</h1>
                            <div>
                                <a class="btn btn-success" href="{% url 'nominals:nominal_create' %}">Create</a>
                            </div>
                        </div>
                        <ul class="mt-4 list-unstyled">
                            {% for nominal in nominals %}                 
                                {% if nominal.level == 0 %}
                                    <li class="font-weight-bold text-black">{{ nominal }}</li>
                                {% elif nominal.level == 1 %}
                                    <li class="pl-2 font-weight-bold text-secondary">{{ nominal }}</li>
                                {% elif nominal.level == 2 %}
                                    <a href="{% url 'nominals:nominal_detail' pk=nominal.pk %}">
                                        <li class="pl-4">{{ nominal }}</li>
                                    </a>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

nominals/templates/nominals/transactions.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    {% include 'accountancy/transactions_css.html' %}
{% endblock head %}

{% block content %}
    <div class="custom-container">
        {% block above_table %}
        <div class="upper mb-5 border-bottom">
            <div class="container mt-5">
                <h1 class="h4 font-weight-bold pb-2 border-bottom">Nominal Transactions</h1>
                <div class="mb-3">
                    <div class="mt-4">
                        <a href="{% url 'nominals:create' %}?t=nj" class="btn btn-sm btn-success mr-2">New Journal</a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock above_table %}
        {% block table %}
        <div class="lower d-flex justify-content-center">
            <div class="container">
                {% include 'accountancy/transactions_table.html' with form=form columns=columns  %}
            </div>
        </div>
        {% endblock table %}
    </div>
{% endblock content %}

{% block modal_forms %}
    {% include 'accountancy/nominal_modal.html' %}
{% endblock modal_forms %}

{% block js %}
    {% load static %}
    <script src="{% static 'accountancy/js/input_grid_selectize.js' %}"></script>
    <script src="{% static 'nominals/js/transaction_search_form.js' %}"></script>
    {% include 'accountancy/transactions_js.html' %}
    <script>
        {% comment %} for the modal window {% endcomment %}
        $(document).ready(function(){
            $("select[name='nominal-parent']").selectize();
        });
    </script>
{% endblock js %}

nominals/templates/nominals/view.html
{% extends 'accountancy/view.html' %}

{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'purchases/css/purchase_input.css' %}">
{% endblock extra_head %}

{% block header_tran %}
    <div class="row">
        <div class="col-auto">
            <p class="font-weight-bold text-nowrap">Date</p>
            <div class="text-nowrap">{{ header.date }}</div>
        </div>
        <div class="col-auto">
            <p class="font-weight-bold text-nowrap">Ref</p>
            <div class="text-nowrap">{{ header.ref }}</div>
        </div>
        <div class="col-auto">
            <p class="font-weight-bold text-nowrap">Transaction Type</p>
            <div class="text-nowrap">{{ header.get_type_display }}</div>
        </div>
    </div>
{% endblock header_tran %}

{% block totals %}
    {% include 'accountancy/totals_inc_goods_without_matching.html' %}        
{% endblock totals %}

{% block modal_forms %}
    <div class="void-modal modal fade" id="voidModal" tabindex="-1" role="dialog" aria-labelledby="voidModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title font-weight-bold" id="voidModalLabel">Confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body small">
                Are you sure you want to void this transaction?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-sm btn-danger void">Void</button>
            </div>
            </div>
        </div>
    </div>
    {% include 'accountancy/audit_transaction.html' %}
{% endblock modal_forms %}

{% block module_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/4.1.0/mustache.min.js" integrity="sha512-HYiNpwSxYuji84SQbCU5m9kHEsRqwWypXgJMBtbRSumlx1iBB6QaxgEBZHSHEGM+fKyCX/3Kb5V5jeVXm0OglQ==" crossorigin="anonymous"></script>
<script src="{% static 'accountancy/js/nominal_transactions.js' %}"></script>
<script>
    function show_clientside_error(messages){
        // sometimes we get a html error from the server, this is for when not
        var template = $("#message_template").html();
        var result = Mustache.render(template, {messages: messages});
        $("body").find(".void-message-error").remove();
        $("body").append(result);
        $(".void-modal").modal("hide");
    }
    function show_server_side_error(message){
        if(!message){
            show_clientside_error([
                {
                    "level": "alert-danger",
                    "message": "Something went wrong.  Please try again later."
                }
            ]);
        }
        var message_html = $(message);
        message_html.addClass("void-message-error").addClass("mt-5");
        var content = message_html.find(".fixed-centre");
        content.removeClass("alert-success")
        content.addClass("alert-danger");
        $("body").find(".void-message-error").remove();
        $("body").append(message_html);
        $(".void-modal").modal("hide");
    }
    $(document).ready(function() {
        $("form.void-form").on("click", function(event) {
            $(".void-modal").modal("show");
        });
        $("button.void").on("click", function() {
            var form = $("form.void-form");
            $.ajax({
                url: form.attr("action"),
                method: "POST",
                data: form.serialize(),
                success: function (data) {
                    if(data.success) {
                        // set cookie or something to say void was successful
                        // server then adds a message which is shown at data.href URL
                        return window.location.href = data.href;
                    }
                    else{
                        console.log(data);
                        show_server_side_error(data.error_message);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log("There was an error creating the new item", jqXHR, textStatus, errorThrown);
                    console.log(jqXHR.responseJSON);
                    if(jqXHR.responseJSON && jqXHR.responseJSON.error_message){
                        show_clientside_error([
                            {
                                "level": "alert-danger",
                                "message": jqXHR.responseJSON.error_message
                            },
                        ]);
                    }
                    else{
                        var message = "Something went wrong.  Please try again later.";
                        if(jqXHR.status == 403){
                            message = "Permission denied to void this particular kind of transaction."
                        }
                        show_clientside_error([
                            {
                                "level": "alert-danger",
                                "message": message
                            }
                        ]);
                    }
                }
            });
        });
    });
</script>
{% endblock module_js %}