proj/urls.py
from django.contrib import admin
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic.base import RedirectView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cashbook/', include("cashbook.urls")),
    path('contacts/', include("contacts.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('nominals/', include("nominals.urls")),
    path('purchases/', include("purchases.urls")),
    path('sales/', include("sales.urls")),
    path('controls/', include("controls.urls")),
    path('users/', include("users.urls")),
    path('users/', include("django.contrib.auth.urls")),
    path('vat/', include("vat.urls")),
    path('', RedirectView.as_view(url=reverse_lazy(
        "dashboard:dashboard")), name="home")
]

purchases/urls.py
from django.urls import path

from .views import (AgeCreditorsReport, CreateTransaction, EditTransaction,
                    LoadPurchaseMatchingTransactions, LoadSuppliers,
                    TransactionEnquiry, ViewTransaction, VoidTransaction)

app_name = "purchases"
urlpatterns = [
    path("create", CreateTransaction.as_view(), name="create"),
    path("edit/<int:pk>", EditTransaction.as_view(), name="edit"),
    path("view/<int:pk>", ViewTransaction.as_view(), name="view"),
    path("void/<int:pk>", VoidTransaction.as_view(), name="void"),
    path("creditors_report", AgeCreditorsReport.as_view(), name="creditors_report"),
    path("load_matching_transactions", LoadPurchaseMatchingTransactions.as_view(),
         name="load_matching_transactions"),
    path("load_suppliers", LoadSuppliers.as_view(), name="load_suppliers"),
    path("transactions", TransactionEnquiry.as_view(), name="transaction_enquiry"),
]

vat/urls.py
from django.urls import path

from vat.views import (LoadVatCodes, VatCreate, VatDetail, VatList,
                       VatTransactionEnquiry, VatUpdate)

app_name = "vat"
urlpatterns = [
    path("load_vat_codes", LoadVatCodes.as_view(), name="load_vat_codes"),
    path("vat_detail/<int:pk>", VatDetail.as_view(), name="vat_detail"),
    path("vat_create", VatCreate.as_view(), name="vat_create"),
    path("vat_edit/<int:pk>", VatUpdate.as_view(), name="vat_edit"),
    path("vat_list", VatList.as_view(), name="vat_list"),
    path("transactions", VatTransactionEnquiry.as_view(), name="transaction_enquiry"),
]

purchases/models.py
from uuid import uuid4

from accountancy.mixins import (CashBookEntryMixin,
                                ControlAccountInvoiceTransactionMixin,
                                ControlAccountPaymentTransactionMixin,
                                VatTransactionMixin)
from accountancy.models import (MatchedHeaders, Transaction, TransactionHeader,
                                TransactionLine)
from contacts.models import Contact
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.shortcuts import reverse
from simple_history import register
from vat.models import Vat


class Supplier(Contact):
    """
    Do not create or update via the Supplier model because it does
    not audit records.  Always use the Contact model instead.
    """
    class Meta:
        proxy = True

    @classmethod
    def simple_history_custom_set_up(cls):
        pass
        # without this it will try to register the Supplier class which is unwanted


class PurchaseTransaction(Transaction):
    module = "PL"
    _vat_type = "i"


class BroughtForwardInvoice(PurchaseTransaction):
    pass


class Invoice(VatTransactionMixin, ControlAccountInvoiceTransactionMixin, PurchaseTransaction):
    pass


class BroughtForwardCreditNote(PurchaseTransaction):
    pass


class CreditNote(Invoice):
    pass


class Payment(CashBookEntryMixin, ControlAccountPaymentTransactionMixin, PurchaseTransaction):
    pass


class BroughtForwardPayment(PurchaseTransaction):
    pass


class Refund(Payment):
    pass


class BroughtForwardRefund(PurchaseTransaction):
    pass


class ModuleTransactions:
    # FIX ME - rename to "no_nominal_required"
    no_analysis_required = [
        ('pbi', 'Brought Forward Invoice'),
        ('pbc', 'Brought Forward Credit Note'),
        ('pbp', 'Brought Forward Payment'),
        ('pbr', 'Brought Forward Refund'),
    ]
    # FIX ME - rename to "nominals_required"
    analysis_required = [
        ("pp", "Payment"),
        ("pr", "Refund"),
        ('pi', 'Invoice'),
        ('pc', 'Credit Note'),
    ]
    no_lines_required = [
        ('pbp', 'Brought Forward Payment'),
        ('pbr', 'Brought Forward Refund'),
        ('pp', 'Payment'),
        ('pr', 'Refund'),
    ]
    lines_required = [
        ('pbi', 'Brought Forward Invoice'),
        ('pbc', 'Brought Forward Credit Note'),
        ('pi', 'Invoice'),
        ('pc', 'Credit Note'),
    ]
    negatives = [
        'pbc',
        'pbp',
        'pp',
        'pc'
    ]
    positives = [
        'pbi',
        'pbr',
        'pr',
        'pi'
    ]
    credits = [
        'pbc',
        'pbp',
        'pp',
        'pc'
    ]
    debits = [
        'pbi',
        'pbr',
        'pr',
        'pi'
    ]
    payment_types = [
        'pbp',
        'pbr',
        'pp',
        'pr'
    ]
    types = no_analysis_required + analysis_required


class PurchaseHeader(ModuleTransactions, TransactionHeader):
    # TO DO - issue an improperly configured warning if all the types are not all the
    # credit types plus the debit types
    cash_book = models.ForeignKey(
        'cashbook.CashBook', on_delete=models.CASCADE, null=True, blank=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    type = models.CharField(
        max_length=3,
        choices=ModuleTransactions.types
    )
    matched_to = models.ManyToManyField(
        'self', through='PurchaseMatching', symmetrical=False)

    class Meta:
        permissions = [
            # enquiry perms
            ("view_transactions_enquiry", "Can view transactions"),
            # report perms
            ("view_age_creditors_report", "Can view aged creditors report"),
            # transaction perms
            ("create_brought_forward_invoice_transaction",
             "Can create brought forward invoice"),
            ("create_brought_forward_credit_note_transaction",
             "Can create brought forward credit note"),
            ("create_brought_forward_payment_transaction",
             "Can create brought forward payment"),
            ("create_brought_forward_refund_transaction", "Can create brought forward refund"),
            ("create_invoice_transaction", "Can create invoice"),
            ("create_credit_note_transaction", "Can create credit note"),
            ("create_payment_transaction", "Can create payment"),
            ("create_refund_transaction", "Can create refund"),
            ("edit_brought_forward_invoice_transaction", "Can edit brought forward invoice"),
            ("edit_brought_forward_credit_note_transaction",
             "Can edit brought forward credit note"),
            ("edit_brought_forward_payment_transaction", "Can edit brought forward payment"),
            ("edit_brought_forward_refund_transaction", "Can edit brought forward refund"),
            ("edit_invoice_transaction", "Can edit invoice"),
            ("edit_credit_note_transaction", "Can edit credit note"),
            ("edit_payment_transaction", "Can edit payment"),
            ("edit_refund_transaction", "Can edit refund"),
            ("view_brought_forward_invoice_transaction", "Can view brought forward invoice"),
            ("view_brought_forward_credit_note_transaction",
             "Can view brought forward credit note"),
            ("view_brought_forward_payment_transaction", "Can view brought forward payment"),
            ("view_brought_forward_refund_transaction", "Can view brought forward refund"),
            ("view_invoice_transaction", "Can view invoice"),
            ("view_credit_note_transaction", "Can view credit note"),
            ("view_payment_transaction", "Can view payment"),
            ("view_refund_transaction", "Can view refund"),
            ("void_brought_forward_invoice_transaction", "Can void brought forward invoice"),
            ("void_brought_forward_credit_note_transaction",
             "Can void brought forward credit note"),
            ("void_brought_forward_payment_transaction", "Can void brought forward payment"),
            ("void_brought_forward_refund_transaction", "Can void brought forward refund"),
            ("void_invoice_transaction", "Can void invoice"),
            ("void_credit_note_transaction", "Can void credit note"),
            ("void_payment_transaction", "Can void payment"),
            ("void_refund_transaction", "Can void refund"),
        ]

    @property
    def cashbook_transaction_factor(self):
        return 1

    def get_type_transaction(self):
        if self.type == "pbi":
            return BroughtForwardInvoice(header=self)
        if self.type == "pbc":
            return BroughtForwardCreditNote(header=self)
        if self.type == "pbp":
            return BroughtForwardPayment(header=self)
        if self.type == "pbr":
            return BroughtForwardRefund(header=self)
        if self.type == "pi":
            return Invoice(header=self)
        if self.type == "pc":
            return CreditNote(header=self)
        if self.type == "pp":
            return Payment(header=self)
        if self.type == "pr":
            return Refund(header=self)

    def get_absolute_url(self):
        return reverse("purchases:view", kwargs={"pk": self.pk})

class PurchaseLine(ModuleTransactions, TransactionLine):
    header = models.ForeignKey(PurchaseHeader, on_delete=models.CASCADE)
    nominal = models.ForeignKey(
        'nominals.Nominal', on_delete=models.CASCADE, null=True, blank=True)
    vat_code = models.ForeignKey(
        Vat, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Vat Code")
    goods_nominal_transaction = models.ForeignKey(
        'nominals.NominalTransaction', null=True, blank=True, on_delete=models.SET_NULL, related_name="purchase_good_line")
    vat_nominal_transaction = models.ForeignKey(
        'nominals.NominalTransaction', null=True, blank=True, on_delete=models.SET_NULL, related_name="purchase_vat_line")
    total_nominal_transaction = models.ForeignKey(
        'nominals.NominalTransaction', null=True, blank=True, on_delete=models.SET_NULL, related_name="purchase_total_line")
    vat_transaction = models.ForeignKey(
        'vat.VatTransaction', null=True, blank=True, on_delete=models.SET_NULL, related_name="purchase_line_vat_transaction")
    type = models.CharField(
        max_length=3,
        choices=PurchaseHeader.types
        # see note on parent class for more info
    )

    # It does not make sense that a line would exist without a nominal transaction but the purchase line is created
    # before the nominal transaction so it must do the create without the id for the nominal transaction

    class Meta:
        ordering = ['line_no']

    @classmethod
    def fields_to_update(cls):
        return [
            "line_no",
            "description",
            "goods",
            "vat",
            "nominal",
            "vat_code",
            "type"
        ]


class PurchaseMatching(MatchedHeaders):
    # matched_by is the header record through which
    # all the other transactions were matched
    matched_by = models.ForeignKey(
        PurchaseHeader,
        on_delete=models.CASCADE,
        related_name="matched_by_these",
    )
    # matched_to is a header record belonging to
    # the set 'all the other transactions' described above
    matched_to = models.ForeignKey(
        PurchaseHeader,
        on_delete=models.CASCADE,
        related_name="matched_to_these"
    )
    matched_by_type = models.CharField(
        max_length=3,
        choices=PurchaseHeader.types
        # see note on parent class for more info
    )
    matched_to_type = models.CharField(
        max_length=3,
        choices=PurchaseHeader.types
        # see note on parent class for more info
    )
    # So we can do for two trans, t1 and t2
    # t1.matched_to_these.all()
    # t2.matched_by_these.all()

    @classmethod
    def get_not_fully_matched_at_period(cls, headers, period):

purchases/templates/purchases/create.html
{% extends 'nominals/create.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block totals %}
    {% if main_header.is_payment_type %}
        {% include 'accountancy/totals_exc_goods_with_matching.html' %}
    {% else %}
        {% include 'accountancy/totals_inc_goods_with_matching.html' %}        
    {% endif %}
{% endblock totals %}

{% block matching %}
<div class="my-4">
    <div class="mb-2">
        <h2 class="h6 font-weight-bold">Matching</h2>
        <small class="form-text text-muted">The transactions you have already selected to match to this new transaction to</small>
    </div>
    <div>
        <div class="d-none matching_transactions_formset">
            {{ match_formset.management_form|crispy }}
        </div>
        <div class="new_matched_transactions_wrapper">
            <table{% if form_id %} id="{{ form_id }}_table"{% endif %} class="table new_matched_transactions">
                {% crispy match_formset %}
                <tbody>
                    {% crispy match_formset.empty_form match_formset.empty_form.helpers.empty_form %}
                </tbody>
                {% comment %} 
                The second line which creates the empty_form after the formset is a just a row.
                The browser looks to then create a surrounding tbody.  To be clearer though I'll define this myself.
                Multiple tbody elements inside a single table is valid HTML.
                {% endcomment %}
            </table>
        </div>
    </div>
</div>
{% endblock matching %}

{% block under_form %}
    {% include 'accountancy/outstanding.html' %}
{% endblock under_form %}

{% block modal_forms %}
    <div class="modal-on-the-fly-forms">
        {% include 'accountancy/on_the_fly.html' %}
        <div class="modal fade" id="new-contact" tabindex="-1" role="dialog"  aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title font-weight-bold" id="contactModalLabel">New Contact</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% crispy contact_form %}
                </div>
            </div>
        </div>
    </div>
{% endblock modal_forms %}

{% block extra_js %}
    {% include 'accountancy/grid_js.html' with header_form=header_form %}
    <script src="{% static 'purchases/js/on_the_fly.js' %}"></script>
{% endblock extra_js %}

{% block module_js %}
    {% include 'accountancy/matching_js.html' %}
{% endblock module_js %}

purchases/templates/purchases/creditors.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'accountancy/css/selectize.css' %}">
    <link rel="stylesheet" href="{% static 'accountancy/css/input_dropdown.css' %}">
    <link rel="stylesheet" href="{% static 'accountancy/css/input_trans_grid.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href"https://cdn.datatables.net/scroller/2.0.2/css/scroller.dataTables.min.css">
    <link rel="stylesheet" href="{% static 'accountancy/css/matching.css' %}">
    {% block extra_head %}
    {% endblock extra_head %}
{% endblock head %}
 
{% block content %}

<div class="cont">
    <div>
        <div class="d-flex justify-content-center">
            <div>
                <div class="border data-grid p-4 position-relative">
                    <div class="form_and_errors_wrapper">
                        {% include 'purchases/creditors_form.html' %}
                    </div>
                    <div class="mt-4 d-flex justify-content-center">
                        <table class="report">
                            <thead>
                                <tr>
                                    {% for col in columns %}
                                        <th>{{ col.label }}</th>
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody class="table-bordered">
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block js %}
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/scroller/2.0.2/js/dataTables.scroller.min.js"></script>
<script src="{% static 'js/selectize.min.js' %}"></script>
<script src="{% static 'accountancy/js/contact_selectize.js' %}"></script>
<script>

    $(document).ready(function(){

            var native_select_widget = $(":input[name='from_supplier']");
            var creation_url = native_select_widget.attr("data-creation-url");
            var form = native_select_widget.attr("data-form");
            var form_field = native_select_widget.attr("data-form-field");
            var load_url = native_select_widget.attr("data-load-url");

            var form_wrapper = $("div.form_and_errors_wrapper");

            function form_init(){

                contact_selectize({
                    select_identifier: ":input[name='from_supplier']",
                    creation_url: creation_url,
                    form: form,
                    form_field: form_field,
                    load_url: load_url
                });

                contact_selectize({
                    select_identifier: ":input[name='to_supplier']",
                    creation_url: creation_url,
                    form: form,
                    form_field: form_field,
                    load_url: load_url
                });

                form_wrapper.find("form").on("submit", function(e){
                    e.preventDefault();
                    report_table.ajax.reload();
                });
            }

            form_init();

            var report_table = $("table.report")
            .DataTable({
                ajax: function(data, callback, settings){
                    data["from_supplier"] = $(":input[name='from_supplier']").val() || "";
                    data["to_supplier"] = $(":input[name='to_supplier']").val() || "";
                    data["period"] = $(":input[name='period']").val() || "";
                    var show_transactions = $(":input[name='show_transactions']").prop("checked");
                    if(show_transactions){
                        data["show_transactions"] = "yes"
                    }
                    $.ajax({
                        url: "{% url 'purchases:creditors_report' %}",
                        type: "GET",
                        data: data,
                        success: function(data, textStatus, jqXHR){
                            if(data.success){
                                callback(data.data);
                            }
                            else{
                                callback(data);
                            }
                            form_wrapper.empty().append($(data.form_html));
                            form_init();
                        },
                        complete: function(jqXHR, textStatus){
                            if(textStatus != "success"){
                                console.log("Failed to get data for report");
                                console.log("logging...");
                                console.log(jqXHR);
                                console.log(textStatus);
                                console.log("end report logging");
                                alert("There was an error, please try again later.");
                            }
                        }
                    });
                },
                columns: [
                    {% for column in columns %}
                        { 'data' : '{{ column.field }}' },
                    {% endfor %}
                ],
                columnDefs: [
                    {"className": "dt-center", "targets": "_all"},
                    {
                        'render': function (data, type, full, meta) {
                            console.log(data);
                            return '<span>' + data + '</span>';
                        },
                        "targets": [2]
                    }
                ],
                dom: 't',
                scrollY: 250,
                deferRender: true,
                scroller: true,
                serverSide: true,
                scrollCollapse: false,
                language: {
                    zeroRecords: "No transactions found"
                }
            });

            var first_drawn = false;

            report_table.on("draw.dt", function(){
                var show_transactions = $(":input[name='show_transactions']").prop("checked");
                if(show_transactions){
                    report_table.columns([1,2,3]).visible(true);
                }
                else{
                    report_table.columns([1,2,3]).visible(false);
                }
                report_table.columns.adjust();
                if(!first_drawn){
                    // it seems we need to set the width of this div otherwise
                    // the table grows as we toggle between 'show' and 'hide'
                    // transactions
                    $("div.dataTables_scroll").width(
                        $("table.report").width()
                    );
                    first_drawn = true;
                }
            });

    });

</script>
{% endblock js %}

purchases/templates/purchases/creditors_form.html
{% load crispy_forms_tags %}
<div>
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            <div class="row"> <!-- add no-gutters to make it narrower -->
                <div class="col-auto align-self-start"> <!-- or align-self-center -->
                    <svg class="bi bi-exclamation-triangle-fill" width="2em" height="2em" viewBox="0 0 16 16" fill="red" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 5zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                    </svg>
                </div>
                <div class="col">
                    <ul class="small">
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}
    {% crispy form %}
</div>

purchases/templates/purchases/transactions.html
{% extends 'nominals/transactions.html' %}

{% load crispy_forms_tags %}

{% block above_table %}
    <div class="upper mb-5 border-bottom">
        <div class="container mt-5">
            <h1 class="h4 font-weight-bold pb-2 border-bottom">Purchase Ledger Transactions</h1>
            <div>
                <div class="mt-4">
                    <a href="{% url 'purchases:create' %}?t=pi" class="btn btn-sm btn-success mr-2">New Invoice</a>
                    <a href="{% url 'purchases:create' %}?t=pc" class="btn btn-sm btn-success mr-2">New Credit Note</a>
                    <a href="{% url 'purchases:create' %}?t=pp" class="btn btn-sm btn-success mr-2">New Payment</a>
                    <a href="{% url 'purchases:create' %}?t=pr" class="btn btn-sm btn-success mr-2">New Refund</a>
                </div>
                <div class="mt-2">
                    <a href="{% url 'purchases:create' %}?t=pbi" class="btn btn-sm btn-success mr-2">New Brought Forward Invoice</a>
                    <a href="{% url 'purchases:create' %}?t=pbc" class="btn btn-sm btn-success mr-2">New Brought Forward Credit Note</a>
                    <a href="{% url 'purchases:create' %}?t=pbp" class="btn btn-sm btn-success mr-2">New Brought Forward Payment</a>
                    <a href="{% url 'purchases:create' %}?t=pbr" class="btn btn-sm btn-success mr-2">New Brought Forward Refund</a>
                </div>
            </div>
            <div class="mt-4">
                <div>
                    <ul class="nav nav-tabs border-0 small">
                        <li class="nav-item">
                            <a class="nav-link group-all color-b-1 font-weight-bold" href="{% url 'purchases:transaction_enquiry' %}?group=a">All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link group-awaiting-payment color-b-1 font-weight-bold" href="{% url 'purchases:transaction_enquiry' %}?group=ap">Awaiting Payment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger group-overdue font-weight-bold" href="{% url 'purchases:transaction_enquiry' %}?group=o">Overdue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link group-paid color-b-1 font-weight-bold" href="{% url 'purchases:transaction_enquiry' %}?group=p">Paid</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock above_table %}

{% block modal_forms %}
    <div class="modal-on-the-fly-forms">
        <div class="modal fade" id="new-contact" tabindex="-1" role="dialog"  aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title font-weight-bold" id="contactModalLabel">New Contact</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% crispy contact_form %}
                </div>
            </div>
        </div>
    </div>
{% endblock modal_forms %}

{% block js %}
    {% load static %}
    <script src="{% static 'purchases/js/transaction_search_form.js' %}"></script>
    {% include 'accountancy/transactions_js.html' %}
    <script>
        $(document).ready(function(){
            function getUrlVars() {
                // https://stackoverflow.com/a/20097994
                var vars = {};
                var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,    
                function(m,key,value) {
                    vars[key] = value;
                });
                return vars;
            }
            var group = getUrlVars()["group"] || "a";
            var group_tabs = {
                a: "a.group-all",
                ap: "a.group-awaiting-payment",
                o: "a.group-overdue",
                p: "a.group-paid"
            };
            $(group_tabs[group]).addClass("active");
        });
    </script>
{% endblock js %}

purchases/templates/purchases/view.html
{% extends 'cashbook/view.html' %}

{% load static %}

{% block header_tran %}
    <div class="row">
        <div class="col-auto">
            <p class="font-weight-bold text-nowrap">From</p>
            <div class="text-nowrap">{{ header.supplier }}</div>
        </div>
        <div class="col-auto">
            <p class="font-weight-bold text-nowrap">Date</p>
            <div class="text-nowrap">{{ header.date }}</div>
        </div>
        <div class="col-auto">
            <p class="font-weight-bold text-nowrap">Due Date</p>
            <div class="text-nowrap">{{ header.due_date }}</div>
        </div>
        <div class="col-auto">
            <p class="font-weight-bold text-nowrap">Ref</p>
            <div class="text-nowrap">{{ header.ref }}</div>
        </div>
        <div class="col-auto">
            <p class="font-weight-bold text-nowrap">Transaction Type</p>
            <div class="text-nowrap">{{ header.get_type_display }}</div>
        </div>
    </div>
{% endblock header_tran %}

{% block totals %}
    {% if header.is_payment_type %}
        {% include 'accountancy/totals_exc_goods_with_matching.html' %}
    {% else %}
        {% include 'accountancy/totals_inc_goods_with_matching.html' %}        
    {% endif %}
{% endblock totals %}

{% block matching %}
    <div class="border data-grid bg-white position-relative">
        <div class="my-4 px-3 py-2">
            <div>
                <h2 class="h6 font-weight-bold">Matching</h2>
            </div>
            <div>
                <div class="matched_transactions_wrapper" data-audit-aspect-section="match">
                    <table class="table existing_matched_transactions">
                        <thead>
                            <tr>
                                <th class="d-none"></th>
                                <th>Type</th>
                                <th>Ref</th>
                                <th>Total</th>
                                <th>Paid</th>
                                <th>Due</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for match in matches %}
                                <tr>
                                    <td class="d-none" data-pk="{{ match.pk }}">{{ match.pk }}</td>
                                    <td>{{ match.type }}</td>
                                    <td>{{ match.ref }}</td>
                                    <td>{{ match.total }}</td>
                                    <td>{{ match.paid }}</td>
                                    <td>{{ match.due }}</td>
                                    <td>{{ match.value }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock matching %}