controls/urls.py
from django.urls import path

from controls.views import (FinancialYearCreate, FinancialYearDetail,
                            FinancialYearList, GroupCreate, GroupDetail,
                            GroupsList, GroupUpdate, ControlsView, UserCreate,
                            UserDetail, UserEdit, UsersList, AdjustFinancialYear, ModuleSettingsUpdate)

app_name = "controls"
urlpatterns = [
    path("", ControlsView.as_view(), name="index"),
    path("module_settings/", ModuleSettingsUpdate.as_view(), name="module_settings"),
    path("financial_year/", FinancialYearList.as_view(), name="fy_list"),
    path("financial_year/create", FinancialYearCreate.as_view(), name="fy_create"),
    path("financial_year/view/<int:pk>",
         FinancialYearDetail.as_view(), name="fy_view"),
    path("financial_year/adjust", AdjustFinancialYear.as_view(), name="fy_adjust"),
    path("groups/", GroupsList.as_view(), name="groups"),
    path("groups/create", GroupCreate.as_view(), name="group_create"),
    path("groups/edit/<int:pk>", GroupUpdate.as_view(), name="group_edit"),
    path("groups/view/<int:pk>", GroupDetail.as_view(), name="group_view"),
    path("users/", UsersList.as_view(), name="users"),
    path("users/create", UserCreate.as_view(), name="user_create"),
    path("users/edit/<int:pk>", UserEdit.as_view(), name="user_edit"),
    path("users/view/<int:pk>", UserDetail.as_view(), name="user_view"),
]

proj/urls.py
from django.contrib import admin
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic.base import RedirectView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cashbook/', include("cashbook.urls")),
    path('contacts/', include("contacts.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('nominals/', include("nominals.urls")),
    path('purchases/', include("purchases.urls")),
    path('sales/', include("sales.urls")),
    path('controls/', include("controls.urls")),
    path('users/', include("users.urls")),
    path('users/', include("django.contrib.auth.urls")),
    path('vat/', include("vat.urls")),
    path('', RedirectView.as_view(url=reverse_lazy(
        "dashboard:dashboard")), name="home")
]

vat/urls.py
from django.urls import path

from vat.views import (LoadVatCodes, VatCreate, VatDetail, VatList,
                       VatTransactionEnquiry, VatUpdate)

app_name = "vat"
urlpatterns = [
    path("load_vat_codes", LoadVatCodes.as_view(), name="load_vat_codes"),
    path("vat_detail/<int:pk>", VatDetail.as_view(), name="vat_detail"),
    path("vat_create", VatCreate.as_view(), name="vat_create"),
    path("vat_edit/<int:pk>", VatUpdate.as_view(), name="vat_edit"),
    path("vat_list", VatList.as_view(), name="vat_list"),
    path("transactions", VatTransactionEnquiry.as_view(), name="transaction_enquiry"),
]

controls/views.py
import re
from functools import reduce
from itertools import chain, groupby

from accountancy.mixins import (ResponsivePaginationMixin,
                                SingleObjectAuditDetailViewMixin)
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.auth.models import Group, User
from django.db import transaction
from django.db.models import prefetch_related_objects
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DetailView, ListView,
                                  TemplateView, UpdateView)
from nominals.models import NominalTransaction
from simple_history.utils import (bulk_create_with_history,
                                  bulk_update_with_history)
from users.mixins import LockDuringEditMixin
from users.models import UserSession

from controls.forms import (UI_PERMISSIONS, AdjustFinancialYearFormset,
                            FinancialYearForm,
                            FinancialYearInlineFormSetCreate, GroupForm,
                            ModuleSettingsForm, PeriodForm, UserForm)
from controls.helpers import PermissionUI
from controls.models import FinancialYear, ModuleSettings, Period
from controls.widgets import CheckboxSelectMultipleWithDataAttr


class ControlsView(LoginRequiredMixin, TemplateView):
    template_name = "controls/controls.html"


class GroupsList(LoginRequiredMixin, ResponsivePaginationMixin, ListView):
    paginate_by = 25
    model = Group
    template_name = "controls/group_list.html"


class IndividualMixin:
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["edit"] = self.edit
        return context_data


class ReadPermissionsMixin:
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        perms = self.get_perms()
        perm_ui = PermissionUI(perms)
        for perm in UI_PERMISSIONS()():
            perm_ui.add_to_group(perm)
        perm_table_rows = perm_ui.create_table_rows()
        context_data["perm_table_rows"] = perm_table_rows
        return context_data

class GroupDetail(
        LoginRequiredMixin,
        PermissionRequiredMixin,
        SingleObjectAuditDetailViewMixin,
        ReadPermissionsMixin,
        IndividualMixin,
        DetailView):
    model = Group
    template_name = "controls/group_detail.html"
    edit = False
    permission_required = "auth.view_group"

    def get_perms(self):
        return self.object.permissions.all()


class GroupUpdate(
        LoginRequiredMixin,
        PermissionRequiredMixin,
        LockDuringEditMixin,
        SingleObjectAuditDetailViewMixin,
        IndividualMixin,
        UpdateView):
    model = Group
    template_name = "controls/group_edit.html"
    success_url = reverse_lazy("controls:groups")
    form_class = GroupForm
    edit = True
    permission_required = "auth.change_group"


class GroupCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Group
    template_name = "controls/group_edit.html"
    success_url = reverse_lazy("controls:groups")
    form_class = GroupForm
    permission_required = "auth.add_group"


class UsersList(LoginRequiredMixin, ListView):
    paginate_by = 25
    model = User
    template_name = "controls/users_list.html"


"""

    The permissions tab in the UI for the user detail and user edit shows BOTH
    the permissions of the groups the user belongs to and the permissions for that particular user.

    In edit mode the user only has the option to change the latter.

"""

user_fields_to_show_in_audit = [
    'is_superuser',
    'username',
    'first_name',
    'last_name',
    'email',
    'is_active',
]


class UserDetail(
        LoginRequiredMixin,
        PermissionRequiredMixin,
        SingleObjectAuditDetailViewMixin,
        ReadPermissionsMixin,
        DetailView):
    model = User
    template_name = "controls/user_detail.html"
    edit = False
    permission_required = "auth.view_user"
    ui_audit_fields = user_fields_to_show_in_audit

    def get_perms(self):
        user = self.object
        user_perms = user.user_permissions.all()
        prefetch_related_objects([user], "groups__permissions__content_type")
        group_perms = [group.permissions.all() for group in user.groups.all()]
        group_perms = list(chain(*group_perms))
        if user_perms and group_perms:
            return list(set(chain(user_perms, group_perms)))
        if user_perms:
            return user_perms
        if group_perms:
            return group_perms


class UserEdit(
        LoginRequiredMixin,
        PermissionRequiredMixin,
        LockDuringEditMixin,
        SingleObjectAuditDetailViewMixin,
        IndividualMixin,
        UpdateView):
    model = User
    form_class = UserForm
    template_name = "controls/user_edit.html"
    success_url = reverse_lazy("controls:users")
    edit = True
    permission_required = "auth.change_user"
    ui_audit_fields = user_fields_to_show_in_audit

    # because 5 db hits are needed for POST
    @transaction.atomic
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_form(self):
        form = self.form_class(**self.get_form_kwargs())
        user = self.object
        prefetch_related_objects([user], "groups__permissions__content_type")
        group_perms = [group.permissions.all()
                       for group in user.groups.all()]  # does hit db again
        group_perms = list(chain(*group_perms))  # does not hit db again
        group_perms = {perm.pk: perm for perm in group_perms}
        self.group_perms = group_perms
        form.fields["user_permissions"].widget.group_perms = group_perms
        return form

    def form_valid(self, form):
        groups = form.cleaned_data.get("groups")
        user_permissions = form.cleaned_data.get("user_permissions")
        # because the group permissions are included in the form i.e. checkboxes are ticked for
        # permissions which belong to only groups and not users, we need to discount all such permissions
        user_permissions = [
            perm for perm in user_permissions if perm.pk not in self.group_perms]
        form.instance.user_permissions.clear()  # hit db
        form.instance.user_permissions.add(*user_permissions)  # hit db
        form.instance.groups.clear()  # hit db
        form.instance.groups.add(*groups)  # hit db
        response = super().form_valid(form)
        # this deletes the current user session
        update_session_auth_hash(self.request, self.object)
        UserSession.objects.create(
            user=self.object, session_id=self.request.session.session_key)
        return response


class UserCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = "controls/user_edit.html"
    success_url = reverse_lazy("controls:users")
    permission_required = "auth.add_user"

    def get_form(self):
        self.form_class.declared_fields["user_permissions"].widget = CheckboxSelectMultipleWithDataAttr(
            attrs={
                "data-option-attrs": [
                    "codename",
                    "content_type__app_label",
                ],
            }
        )
        form = super().get_form()
        return form


class FinancialYearList(ListView):
    model = FinancialYear
    template_name = "controls/fy_list.html"


def convert_month_years_to_full_dates(post_data_copy):
    for k, v in post_data_copy.items():
        if re.search(r"month_start", k):
            if v:
                v = "01-" + v
                if re.search(r"01-\d{2}-\d{4}", v):
                    post_data_copy[k] = v
    return post_data_copy


class FinancialYearCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = FinancialYear
    template_name = 'controls/fy_create.html'
    form_class = FinancialYearForm
    success_url = reverse_lazy("controls:index")
    permission_required = "controls.add_financialyear"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.POST:
            d = convert_month_years_to_full_dates(self.request.POST.copy())
            context_data["periods"] = FinancialYearInlineFormSetCreate(
                d, prefix="period")
        else:
            context_data["periods"] = FinancialYearInlineFormSetCreate(
                prefix="period")
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        periods = context_data["periods"]
        if periods.is_valid():
            fy = form.save()
            self.object = fy
            periods.instance = fy
            periods.save(commit=False)
            period_instances = [p.instance for p in periods]
            period_instances.sort(key=lambda p: p.month_start)
            i = 1
            for period in period_instances:
                period.fy_and_period = f"{fy.financial_year}{str(i).rjust(2, '0')}"
                period.period = str(i).rjust(2, '0')
                i = i + 1
            bulk_create_with_history(
                [*period_instances],
                Period
            )
            first_period_of_fy = fy.first_period()
            mod_settings = ModuleSettings.objects.first()
            # when a FY is created for the first time we need to set the default
            # posting periods for each posting module in the software
            for setting, period in mod_settings.module_periods().items():
                if not period:
                    setattr(mod_settings, setting, first_period_of_fy)

controls/templates/controls/controls.html
{% extends 'base.html' %}

{% block content %}
<div class="cont">
    <div>
        <div class="container">
            <div class="mt-5">
                <div class="border p-4">
                    <h1 class="h4 font-weight-bold mb-4">Settings</h1>
                    <div class="row">
                        <div class="col-6">
                            <ul class="list-group">
                                <a href="{% url 'controls:groups' %}" class="list-group-item list-group-item-action">
                                    <div class="text-primary">Groups</div>
                                    <small class="text-muted">Add, remove or modify groups</small>
                                </a>
                                <a href="{% url 'controls:users' %}" class="list-group-item list-group-item-action">
                                    <div class="text-primary">Users</div>
                                    <small class="text-muted">Add, remove or modify users</small>
                                </a>
                            </ul>
                        </div>
                        <div class="col-6">
                            <ul class="list-group">
                                <a href="{% url 'controls:fy_list' %}" class="list-group-item list-group-item-action">
                                    <div class="text-primary">Financial Years</div>
                                    <small class="text-muted">Add, remove or modify financial years</small>
                                </a>
                                <a href="{% url 'controls:module_settings' %}" class="list-group-item list-group-item-action">
                                    <div class="text-primary">Module Settings</div>
                                    <small class="text-muted">Edit the current period of a module / ledger e.g. Cash Book</small>
                                </a>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

controls/templates/controls/fy_detail.html
{% extends 'accountancy/single_object_detail_with_audit.html' %}

{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'accountancy/css/selectize.css' %}">
    <link rel="stylesheet" href="{% static 'controls/css/fy.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/css/tempusdominus-bootstrap-4.min.css" integrity="sha512-3JRrEUwaCkFUBLK1N8HehwQgu8e23jTH4np5NHOmQOobuC4ROQxFwFgBLTnhcnQRMs84muMh0PnnwXlPq5MGjg==" crossorigin="anonymous" />
{% endblock extra_head %}

{% block content %}
<div class="cont">
    <div>
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="border data-grid p-4" style="width: 400px;">
                    <div class="border-bottom">
                        <div>
                            <div class="input-group" style="height: 48px;">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="fy-span" style="width:120px;">FY</span>
                                </div>
                                <div class="font-weight-bold div_input form-control">{{ financial_year.financial_year }}</div>
                            </div>
                            <div>
                                {% for period in periods %}
                                    <div class="input-group" style="height: 48px;">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text period-number" style="height: 48px; width:120px;">Period 1</span>
                                        </div>
                                        <div class="div_input form-control">{{ period.month_start|date:"M Y" }}</div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

controls/templates/controls/fy_list.html
{% extends 'controls/list.html' %}

{% block header %}Financial Years{% endblock header %}

{% block actions %}
<div>
    <a href="{% url 'controls:fy_adjust' %}" class="btn-primary btn">Adjust</a>
    <a href="{% url 'controls:fy_create' %}" class="btn-primary btn">Create Financial Year</a>
</div>
{% endblock actions %}

{% block object %}
    <a href="{% url 'controls:fy_view' pk=object.pk %}" class="list-group-item list-group-item-action">
        <div class="text-primary">{{ object.financial_year }}</div>
    </a>
{% endblock object %}

controls/templates/controls/group_edit.html
{% extends 'controls/group_base.html' %}

{% load crispy_forms_tags %}

{% block group_content %}
    {% include 'accountancy/crispy_form_non_field_errors.html' %}
    <form method="POST" action="">
    {% csrf_token %}
    {% crispy form %}
    <h2 class="my-3 h6">Permissions</h2>
    {% include 'controls/group_content_for_edit.html' %}
    <div class="d-flex justify-content-end">
        <a class="btn btn-secondary mr-2" href="{% url 'controls:groups' %}">Cancel</a>
        <button class="btn btn-success">Save</button>
    </div>
{% endblock group_content %}

controls/templates/controls/group_list.html
{% extends 'controls/list.html' %}

{% block header %}Groups{% endblock header %}

{% block actions %}
<div>
    <a class="btn btn-success" href="{% url 'controls:group_create' %}">Create</a>
</div>
{% endblock actions %}

{% block object %}
    <a href="{% url 'controls:group_view' pk=object.pk %}" class="list-group-item list-group-item-action">
        <div class="text-primary">{{ object.name }}</div>
    </a>
{% endblock object %}

controls/templates/controls/list.html
{% extends 'base.html' %}

{% block content %}
<div class="cont">
    <div>
        <div class="container">
            <div class="mt-5">
                <div class="border p-4">
                    <div class="d-flex justify-content-between">
                        <h1 class="h4 font-weight-bold mb-4">{% block header %}{% endblock header %}</h1>
                        {% block actions %}
                        {% endblock actions %}
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <ul class="list-group">
                               {% for object in object_list %}
                                    {% block object %}
                                    {% endblock object %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'pagination.html' %}

{% endblock content %}

controls/templates/controls/module_settings.html
{% extends 'controls/fy_detail.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="cont">
    <div>
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="border data-grid p-4" style="width: 600px;">
                    <div>
                        <div>
                            <div>
                                <div class="text-right">
                                    <button class="btn btn-primary audit-btn">Audit</button>
                                </div>
                                {% if form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <div class="row">
                                            <div class="col">
                                                <ul class="list-unstyled m-0 p-0">
                                                    {% for error in form.non_field_errors %}
                                                        <li>{{ error }}</li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                            {% crispy form %}
                            <div class="mt-3 d-none audit_section p-3 border rounded">
                                <h2 class="h4 font-weight-bold">Audit</h2>
                                {% include 'accountancy/audit.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

controls/templates/controls/perm_object_detail.html
{% load utility_tags %}
{% if row.module %}
<tr>
    <td><div>{{ row.module.title }}</div></td>
    <td><div class="ml-3">{{ row.section|title}}</div></td>
    <td><div class="ml-5">{{ row.object|field_to_label }}</div></td>
    <td>
        <div class="d-flex justify-content-center align-items-center">
            {% block create_field %}
                {{ row.create_field }}
            {% endblock create_field %}
        </div>
    </td>
    <td>
        <div class="d-flex justify-content-center align-items-center">
            {% block edit_field %}
                {{ row.edit_field }}
            {% endblock edit_field %}
        </div>
    </td>
    <td>
        <div class="d-flex justify-content-center align-items-center">
            {% block view_field %}
                {{ row.view_field }}
            {% endblock view_field %}
        </div>
    </td>
    <td>
        <div class="d-flex justify-content-center align-items-center">
            {% block void_field %}
                {{ row.void_field }}
            {% endblock void_field %}
        </div>
    </td>
</tr>
{% endif %}

controls/templates/controls/perm_object_edit.html
{% extends 'controls/perm_object_detail.html' %}

{% block create_field %}
    {% if row.create_field %}
        {% include "django/forms/widgets/input.html" with widget=row.create_field %}
    {% endif %}
{% endblock create_field %}

{% block edit_field %}
    {% if row.edit_field %}
        {% include "django/forms/widgets/input.html" with widget=row.edit_field %}
    {% endif %}
{% endblock edit_field %}

{% block view_field %}
    {% if row.view_field %}
        {% include "django/forms/widgets/input.html" with widget=row.view_field %}
    {% endif %}
{% endblock view_field %}

{% block void_field %}
    {% if row.void_field %}
        {% include "django/forms/widgets/input.html" with widget=row.void_field %}
    {% endif %}
{% endblock void_field %}

controls/templates/controls/perm_table.html
{% for group, row, index in widget.optgroups %}
    {% include row.template_name with row=row %}
{% endfor %}

controls/templates/controls/table_formset.html
{% load crispy_forms_tags %}
<div class="formset">
    {{ formset.management_form|crispy }}
    <table class="table">
        <thead>
            <tr>
                <th>Period</th>
                <th>Calendar Month</th>
                <th>Financial Year</th>
            </tr>
        </thead>
        <tbody>
            {% for form in formset.forms %}
                {% crispy form %}
            {% endfor %}
        </tbody>
    </table>
</div>

controls/templates/controls/user_base.html
{% extends 'accountancy/single_object_detail_with_audit.html' %}

{% load static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowgroup/1.1.2/css/rowGroup.dataTables.min.css">
    <link rel="stylesheet" href="{% static 'accountancy/css/selectize.css' %}">
    <link rel="stylesheet" href="{% static 'controls/css/perms_table.css' %}">
{% endblock extra_head %}

{% block content %}
<div class="cont">
    <div>
        <div class="container">
            <div class="mt-5">
                <div class="border p-4">
                    <div>
                        <div class="d-flex justify-content-between border-bottom">
                            <ul class="nav nav-tabs border-bottom-0">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#collapse_main" role="button" data-toggle="tab" aria-expanded="false" aria-controls="collapse_main">Main</a>
                                </li>
                                <li class="nav-item">
                                    <a  class="nav-link" href="#collapse_permission" role="button" data-toggle="tab" aria-expanded="false" aria-controls="collapse_permission">Permissions</a>
                                </li>
                            </ul>
                            {% block actions %}
                            {% endblock actions %}
                        </div>
                        {% block user_content %}
                        {% endblock user_content %}
                        <div class="mt-3 d-none audit_section p-3 border rounded">
                            <h2 class="h4 font-weight-bold">Audit</h2>
                            {% include 'accountancy/audit.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block module_js %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/rowgroup/1.1.2/js/dataTables.rowGroup.min.js"></script>
<script src="{% static 'js/selectize.min.js' %}"></script>
<script src="{% static 'controls/js/perms_table.js' %}"></script>
<script>
    $('#id_groups').selectize({
        maxItems: null,
        render: {
            item: function(data, escape){
                return "<div class='item btn' data-value='" + escape(data.value) + "'>" + escape(data.text) + "</div>";
            }
        }
    });
</script>
{% endblock module_js %}

controls/templates/controls/user_edit.html
{% extends 'controls/user_detail.html' %}

{% load crispy_forms_tags %}

{% block user_content %}
    <form method="POST" action="">
        {% csrf_token %}
        {% include 'controls/user_content_for_edit.html' %}
    </form>
{% endblock user_content %}

controls/templates/controls/users_list.html
{% extends 'controls/list.html' %}

{% block header %}Users{% endblock header %}

{% block actions %}
<div>
    <a class="btn btn-success" href="{% url 'controls:user_create' %}">Create</a>
</div>
{% endblock actions %}

{% block object %}
    <a href="{% url 'controls:user_view' pk=object.pk %}" class="d-flex justify-content-between list-group-item list-group-item-action">
        <div class="text-primary">{{ object.username }}</div>
        <div>
            <small class="text-muted">Last logged in at : {{ object.last_login }}</small>
        </div>
    </a>
{% endblock object %}