cashbook/urls.py
from django.urls import path

from .views import (CashBookCreate, CashBookDetail, CashBookEdit, CashBookList,
                    CreateTransaction, EditTransaction, TransactionEnquiry,
                    ViewTransaction, VoidTransaction)

app_name = "cashbook"
urlpatterns = [
    path("create", CreateTransaction.as_view(), name="create"),
    path("edit/<int:pk>", EditTransaction.as_view(), name="edit"),
    path("view/<int:pk>", ViewTransaction.as_view(), name="view"),
    path("void/<int:pk>", VoidTransaction.as_view(), name="void"),
    path("transactions", TransactionEnquiry.as_view(), name="transaction_enquiry"),

    path("cashbook_create", CashBookCreate.as_view(), name="cashbook_create"),
    path("cashbook_list", CashBookList.as_view(), name="cashbook_list"),
    path("cashbook_detail/<int:pk>",
         CashBookDetail.as_view(), name="cashbook_detail"),
    path("cashbook_edit/<int:pk>", CashBookEdit.as_view(), name="cashbook_edit"),
]

contacts/urls.py
from django.urls import path

from contacts.views import (ContactDetail, ContactListView, ContactUpdate,
                            CreateContact)

app_name = "contacts"
urlpatterns = [
    path("", ContactListView.as_view(), name="list"),
    path("create", CreateContact.as_view(), name="create"),
    path("<int:pk>", ContactDetail.as_view(), name="detail"),
    path("edit/<int:pk>", ContactUpdate.as_view(), name="edit"),
]

proj/urls.py
from django.contrib import admin
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic.base import RedirectView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cashbook/', include("cashbook.urls")),
    path('contacts/', include("contacts.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('nominals/', include("nominals.urls")),
    path('purchases/', include("purchases.urls")),
    path('sales/', include("sales.urls")),
    path('controls/', include("controls.urls")),
    path('users/', include("users.urls")),
    path('users/', include("django.contrib.auth.urls")),
    path('vat/', include("vat.urls")),
    path('', RedirectView.as_view(url=reverse_lazy(
        "dashboard:dashboard")), name="home")
]

sales/urls.py
from django.urls import path

from .views import (AgeDebtorsReport, CreateTransaction, EditTransaction,
                    LoadCustomers, LoadSaleMatchingTransactions,
                    TransactionEnquiry, ViewTransaction, VoidTransaction)

app_name = "sales"
urlpatterns = [
    path("create", CreateTransaction.as_view(), name="create"),
    path("edit/<int:pk>", EditTransaction.as_view(), name="edit"),
    path("view/<int:pk>", ViewTransaction.as_view(), name="view"),
    path("void/<int:pk>", VoidTransaction.as_view(), name="void"),
    path("debtors_report", AgeDebtorsReport.as_view(), name="debtors_report"),

    path("load_matching_transactions", LoadSaleMatchingTransactions.as_view(),
         name="load_matching_transactions"),
    path("load_customers", LoadCustomers.as_view(), name="load_customers"),
    path("transactions", TransactionEnquiry.as_view(), name="transaction_enquiry"),
]

users/urls.py
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

from users.views import (Profile, SignIn, SignUp, UserPasswordResetConfirmView,
                         UserPasswordResetView, unlock)

app_name = "users"
urlpatterns = [
    path('login', RedirectView.as_view(url=reverse_lazy(
        "users:signin")), name="login"),
    path("password_reset", UserPasswordResetView.as_view(), name="password_reset"),
    path("reset/<uidb64>/<token>/", UserPasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("profile", Profile.as_view(), name="profile"),
    path("signup", SignUp.as_view(), name="signup"),
    path("signin", SignIn.as_view(redirect_authenticated_user=True), name="signin"),
    path("unlock/<int:pk>", unlock, name="unlock")
]

vat/urls.py
from django.urls import path

from vat.views import (LoadVatCodes, VatCreate, VatDetail, VatList,
                       VatTransactionEnquiry, VatUpdate)

app_name = "vat"
urlpatterns = [
    path("load_vat_codes", LoadVatCodes.as_view(), name="load_vat_codes"),
    path("vat_detail/<int:pk>", VatDetail.as_view(), name="vat_detail"),
    path("vat_create", VatCreate.as_view(), name="vat_create"),
    path("vat_edit/<int:pk>", VatUpdate.as_view(), name="vat_edit"),
    path("vat_list", VatList.as_view(), name="vat_list"),
    path("transactions", VatTransactionEnquiry.as_view(), name="transaction_enquiry"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'accountancy/css/style.css' %}">
    {% block head %}
    {% endblock head %}
  </head>
  <body>
    <header class="header-nav bg-primary-blue font-weight-bold">
      <nav class="navbar navbar-expand-lg text-white">
        <div class="collapse navbar-collapse justify-content-between" id="companyNavDropDown">
          <ul class="navbar-nav">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Demo Company (UK)
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <div class="p-3 small font-weight-bold">Demo Company (UK)</div>
                    <a class="dropdown-item" href="{% url 'controls:index' %}">Settings</a>
                </div>
            </div>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" id="purchasesMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Purchases
              </a>
              <div class="dropdown-menu" aria-labelledby="purchasesMenuLink">
                <a class="dropdown-item" href="{% url 'purchases:transaction_enquiry' %}">View Transactions</a>
                <a class="dropdown-item" href="{% url 'purchases:create' %}">Post Transaction</a>
                <a class="dropdown-item" href="{% url 'purchases:creditors_report' %}">Age Creditors Report</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" id="salesMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sales
              </a>
              <div class="dropdown-menu" aria-labelledby="salesMenuLink">
                <a class="dropdown-item" href="{% url 'sales:transaction_enquiry' %}">View Transactions</a>
                <a class="dropdown-item" href="{% url 'sales:create' %}">Post Transaction</a>
                <a class="dropdown-item" href="{% url 'sales:debtors_report' %}">Age Debtors Report</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" id="nominalMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Nominal
              </a>
              <div class="dropdown-menu" aria-labelledby="nominalMenuLink">
                <a class="dropdown-item" href="{% url 'nominals:transaction_enquiry' %}">View Transactions</a>
                <a class="dropdown-item" href="{% url 'nominals:create' %}">Post Transaction</a>
                <a class="dropdown-item" href="{% url 'nominals:trial_balance' %}">Trial Balance</a>
                <a class="dropdown-item" href="{% url 'nominals:nominals_list' %}">Nominals</a>
                <div class="dropdown dropright">
                    <a class="dropdown-item dropdown-toggle pointer" id="dropdown-fy" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Financial Year Ends</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown-fy">
                        <a class="dropdown-item text-capitalize" href="{% url 'nominals:finalise_fy' %}">finalise</a>
                        <a class="dropdown-item text-capitalize" href="{% url 'nominals:rollback_fy' %}">rollback</a>
                    </div>
                </div>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" id="cashbookMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Cash Book
              </a>
              <div class="dropdown-menu" aria-labelledby="cashbookMenuLink">
                <a class="dropdown-item" href="{% url 'cashbook:transaction_enquiry' %}">View Transactions</a>
                <a class="dropdown-item" href="{% url 'cashbook:create' %}">Post Transaction</a>
                <a class="dropdown-item" href="{% url 'cashbook:cashbook_list' %}">Cashbooks</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" id="vatMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Vat
              </a>
              <div class="dropdown-menu" aria-labelledby="vatMenuLink">
                <a class="dropdown-item" href="{% url 'vat:transaction_enquiry' %}">View Transactions</a>
                <a class="dropdown-item" href="{% url 'vat:vat_list' %}">Vat Codes</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" id="contactsMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Contacts
              </a>
              <div class="dropdown-menu" aria-labelledby="contactsMenuLink">
                <a class="dropdown-item" href="{% url 'contacts:list' %}?q=all">All</a>
                <a class="dropdown-item" href="{% url 'contacts:list' %}?q=customers">Customers</a>
                <a class="dropdown-item" href="{% url 'contacts:list' %}?q=suppliers">Suppliers</a>
              </div>
            </li>
          </ul>
          <ul class="nav-bar nav">
            <li class="dropdown">
              <a class="nav-link dropdown-toggle" id="userMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ request.user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenuLink">
                <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    {% block content %}
    {% endblock content %}

    {% block modal_forms %}
    {% endblock modal_forms %}

    {% if locked_by_another %}
        {% include 'accountancy/edited_by_another.html' %}
    {% endif %}

    {% if unlock_url %}
        {% include 'accountancy/unlock_form.html' with action=unlock_url %}
    {% endif %}

    {% include 'messages.html' with messages=messages %}
    {% include 'messages_clientside.html' %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap_multi_level_dropdown.js' %}"></script>
    {% block js %}
        {% block extra_js %}
        {% endblock extra_js %}
        {% block module_js %}
        {% endblock module_js %}
    {% endblock js %}
    <script src="{% static 'accountancy/js/content_loaded.js' %}"></script>
    <script src="{% static 'accountancy/js/reload.js' %}"></script>
    <script>
        $(document).ready(function(){
            var locked_by_another = '{{ locked_by_another }}';
            if(locked_by_another){
                $("#edited_by_another_modal").modal("show");
                $("#edited_by_another_modal").on("hide.bs.modal", function(e){
                    e.preventDefault();
                    e.stopPropagation();
                });
            }
            var unlocked = false;
            var before_unload_began;
            function unlock() {
                var unlock_form = $("form.unlock_form");
                if(unlock_form.length){
                    $.ajax({
                        type: "POST",
                        url: unlock_form.attr("action"),
                        data: unlock_form.serialize(),
                        success: function (data) {
                            unlocked = true; // we assume
                        }
                    })
                }
            }
            window.addEventListener('beforeunload', function(event){
                before_unload_began = Date.now();
                unlock();
                while(!unlocked){
                    if(Date.now() - before_unload_began > 100){
                        return; // never wait longer than 100 ms
                    }
                }
            });
        });
    </script>
  </body>
</html>

templates/messages.html
{% if messages %}
    <div class="position-absolute fixed-centre">
        {% for message in messages %}
                <div class="mt-1 fixed-centre alert {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} alert-success {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} alert-warning{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} alert-danger{% else %} alert-info {% endif %} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
        {% endfor %}
    </div>
{% endif %}

templates/messages_clientside.html
<script type="text/template" id="message_template">
    {% verbatim  %}
        <div class="position-absolute fixed-centre">
            {{#messages}}
                <div class="mt-1 fixed-centre alert {{ level }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {{/messages}}
        </div>
    {% endverbatim  %}
</script>

templates/pagination.html
{% load utility_tags %}

{% autoescape off %}
    {% if page_obj.has_other_pages %}
        <nav aria-label="pagination">
        <ul class="mt-4 pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link"
                    href="{% modify_query page=page_obj.previous_page_number %}">
                &laquo;</a></li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span></span></li>
            {% endif %}

            {% for page_number in page_range %}
                {% if page_number == page_obj.number %}
                <li class="page-item active">
                    <span class="page-link">{{ page_number }}
                        <span class="sr-only">(current)</span></span>
                </li>

                {% elif page_number > 0 and page_number <= page_obj.paginator.num_pages %}

                    {% if page_number > lower_page_on_xs and page_number < upper_page_on_xs %}
                    {% comment %} will show on smallest devices {% endcomment %}
                        <li class="page-item">
                            <a class="page-link"
                            href="{% modify_query page=page_number %}">
                                {{ page_number }}</a>
                        </li>
                    {% else %}
                    {% comment %} will hide on smallest devices {% endcomment %}
                        <li class="page-item">
                            <a class="page-link d-none d-md-block"
                            href="{% modify_query page=page_number %}">
                                {{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                    href="{% modify_query page=page_obj.next_page_number %}">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span></a></li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span></span>
            </li>
            {% endif %}

        </ul>
        </nav>
    {% endif %}
{% endautoescape %}